// <auto-generated />
using System;
using BaseCore.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BaseCore.Infrastructure.Migrations
{
    [DbContext(typeof(BaseContext))]
    [Migration("20181112102643_D201811123")]
    partial class D201811123
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BeCore.Core.Model.BussCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApplicationId");

                    b.Property<string>("ApplicationName");

                    b.Property<string>("CodeNum");

                    b.Property<string>("CodeRemark");

                    b.Property<DateTime>("CreateTime");

                    b.Property<DateTime?>("DeleteTime");

                    b.Property<bool>("Deleted");

                    b.Property<bool>("IsPublic");

                    b.HasKey("Id");

                    b.ToTable("BussCode");
                });

            modelBuilder.Entity("BeCore.Core.Model.BussCodeInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<DateTime?>("DeleteTime");

                    b.Property<bool>("Deleted");

                    b.Property<string>("LanguageCode");

                    b.Property<string>("LanguageRemark");

                    b.Property<string>("MsgInfo");

                    b.Property<int>("ParentId");

                    b.HasKey("Id");

                    b.ToTable("BussCodeInfo");
                });

            modelBuilder.Entity("BeCore.Core.Model.Sys_Buttons", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ButtonHtml");

                    b.Property<string>("ButtonTag");

                    b.Property<string>("ButtonText");

                    b.Property<DateTime>("CreateTime");

                    b.Property<DateTime?>("DeleteTime");

                    b.Property<bool>("Deleted");

                    b.Property<string>("IconUrl");

                    b.Property<string>("Remark");

                    b.Property<string>("Sortnum");

                    b.Property<string>("iconCls");

                    b.HasKey("Id");

                    b.ToTable("Sys_Buttons");
                });

            modelBuilder.Entity("BeCore.Core.Model.Sys_Departments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<DateTime?>("DeleteTime");

                    b.Property<bool>("Deleted");

                    b.Property<string>("DepartmentName");

                    b.Property<int>("ParentId");

                    b.Property<string>("Remark");

                    b.Property<string>("Sortnum");

                    b.HasKey("Id");

                    b.ToTable("Sys_Departments");
                });

            modelBuilder.Entity("BeCore.Core.Model.Sys_NavButtons", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ButtonId");

                    b.Property<DateTime>("CreateTime");

                    b.Property<DateTime?>("DeleteTime");

                    b.Property<bool>("Deleted");

                    b.Property<int>("NavId");

                    b.Property<string>("Sortnum");

                    b.HasKey("Id");

                    b.ToTable("Sys_NavButtons");
                });

            modelBuilder.Entity("BeCore.Core.Model.Sys_Navigations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BigImageUrl");

                    b.Property<DateTime>("CreateTime");

                    b.Property<DateTime?>("DeleteTime");

                    b.Property<bool>("Deleted");

                    b.Property<string>("IsVisible");

                    b.Property<string>("Linkurl");

                    b.Property<string>("NavTag");

                    b.Property<string>("NavTitle");

                    b.Property<int>("ParentID");

                    b.Property<string>("Sortnum");

                    b.Property<string>("iconCls");

                    b.Property<string>("iconUrl");

                    b.HasKey("Id");

                    b.ToTable("Sys_Navigations");
                });

            modelBuilder.Entity("BeCore.Core.Model.Sys_Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddTime");

                    b.Property<string>("ConfigJson");

                    b.Property<DateTime>("CreateTime");

                    b.Property<DateTime?>("DeleteTime");

                    b.Property<bool>("Deleted");

                    b.Property<int>("DepartmentId");

                    b.Property<string>("Email");

                    b.Property<bool>("IsAdmin");

                    b.Property<bool>("IsDisabled");

                    b.Property<string>("Mobile");

                    b.Property<string>("PassSalt");

                    b.Property<string>("Password");

                    b.Property<string>("QQ");

                    b.Property<string>("Remark");

                    b.Property<string>("TrueName");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Sys_Users");
                });
#pragma warning restore 612, 618
        }
    }
}
